COMPOSE_PROJECT_NAME={{PROJECT_NAME}}

DOMAIN={{DOMAIN}}
DOMAIN_LCL={{DOMAIN_LCL}}

HTTP_PORT=80
HTTPS_PORT=443

API_DIR=../api
FRONT_DIR=../front
{{#if ADMIN_ENABLED}}
ADMIN_DIR=../admin
{{/if}}
{{#if MOBILE_ENABLED}}
MOBILE_DIR=../mobile
{{/if}}

API_INTERNAL_PORT={{API_INTERNAL_PORT}}
FRONT_INTERNAL_PORT={{FRONT_INTERNAL_PORT}}
{{#if ADMIN_ENABLED}}
ADMIN_INTERNAL_PORT={{ADMIN_INTERNAL_PORT}}
{{/if}}

XDEBUG_MODE=debug
XDEBUG_START_WITH_REQUEST=yes
XDEBUG_CLIENT_HOST=host.docker.internal
XDEBUG_CLIENT_PORT=9003
XDEBUG_IDEKEY={{PROJECT_NAME}}
PHP_IDE_CONFIG={{PROJECT_NAME}}